### ISSUE TITLE
Messages are displayed twice

### ISSUE THREAD

**Issue by DominikDolezel** [DislikesSchool/EduPage2#111]
Each message is twice in my feed.

**Comment by vyPal** [comment]
This bug has been fixed with a patch. Please make sure that you are using the latest version of the EduPage2 app ([v1.7.6](https://github.com/DislikesSchool/EduPage2/releases/tag/v1.7.6)), then launch the app, wait a couple of seconds for the patch to download and restart the app. Once restarted, the bug should be resolved.
