### ISSUE TITLE
Timetable doesn't fit on page

### ISSUE THREAD

**Issue by DominikDolezel** [DislikesSchool/EduPage2#112]
**Describe the bug**
There are too many lessons, they don't fit on the page and the page is not scrollable.

**To Reproduce**
have too many lessons ig

**Expected behavior**
I suppose you should be able to scroll down, which is not possible rn

**Comment by vyPal** [comment]
This bug has been fixed with a patch. Please make sure that you are using the latest version of the EduPage2 app ([v1.7.6](https://github.com/DislikesSchool/EduPage2/releases/tag/v1.7.6)), then launch the app, wait a couple of seconds for the patch to download and restart the app. Once restarted, the bug should be resolved.
